export const GET_ALL_CALENDARS = "GET_ALL";
export const TOGGLE_CALENDAR = "TOGGLE_CALENDAR";
export const GET_INITIAL_INFO = "GET_INITIAL_INFO";
export const CREATE_CALENDAR = "CREATE_CALENDAR";
export const CREATE_CALENDAR_FAIL = "CREATE_CALENDAR_FAIL";
export const OPEN_CREATE_MODAL = "OPEN_CREATE_MODAL";
